export const mockData = [
  {
    name: "Training #1",
    date: "27-05-2019",
    program: [
      {
        excersise: "Squat",
        sets: [
          { reps: 8, weight: 85, workingSet: false },
          { reps: 7, weight: 125, workingSet: false },
          { reps: 6, weight: 147.5, workingSet: false },
          { reps: 5, weight: 157.5, workingSet: false },
          { reps: 5, weight: 157.5, workingSet: false },
          { reps: 4, weight: 170, workingSet: true },
          { reps: 4, weight: 170, workingSet: true },
          { reps: 4, weight: 170, workingSet: true },
          { reps: 4, weight: 170, workingSet: true },
          { reps: 4, weight: 170, workingSet: true },
          { reps: 4, weight: 170, workingSet: true },
        ],
      },
      {
        excersise: "Bench Press",
        sets: [
          { reps: 8, weight: 65, workingSet: false },
          { reps: 7, weight: 87.5, workingSet: false },
          { reps: 6, weight: 100, workingSet: false },
          { reps: 4, weight: 110, workingSet: false },
          { reps: 4, weight: 110, workingSet: false },
          { reps: 3, weight: 115, workingSet: true },
          { reps: 3, weight: 115, workingSet: true },
          { reps: 3, weight: 115, workingSet: true },
          { reps: 3, weight: 115, workingSet: true },
          { reps: 3, weight: 115, workingSet: true },
          { reps: 3, weight: 115, workingSet: true },
        ],
      },
    ],
  },
  {
    name: "Training #2",
    date: "29-05-2019",
    program: [
      {
        excersise: "High-bar squat",
        sets: [
          { reps: 5, weight: 70, workingSet: false },
          { reps: 5, weight: 70, workingSet: false },
          { reps: 5, weight: 100, workingSet: false },
          { reps: 5, weight: 120, workingSet: true },
          { reps: 5, weight: 120, workingSet: true },
          { reps: 5, weight: 120, workingSet: true },
          { reps: 5, weight: 120, workingSet: true },
        ],
      },
      {
        excersise: "Bench Press feet-up",
        sets: [
          { reps: 5, weight: 60, workingSet: false },
          { reps: 5, weight: 60, workingSet: false },
          { reps: 5, weight: 80, workingSet: false },
          { reps: 5, weight: 102.5, workingSet: true },
          { reps: 5, weight: 102.5, workingSet: true },
          { reps: 5, weight: 102.5, workingSet: true },
          { reps: 5, weight: 102.5, workingSet: true },
        ],
      },
      {
        excersise: "Close grip bench press",
        sets: [
          { reps: 5, weight: 100, workingSet: true },
          { reps: 5, weight: 100, workingSet: true },
          { reps: 5, weight: 100, workingSet: true },
        ],
      },
      {
        excersise: "Deadlift",
        sets: [
          { reps: 6, weight: 120, workingSet: false },
          { reps: 5, weight: 140, workingSet: false },
          { reps: 4, weight: 160, workingSet: false },
          { reps: 2, weight: 175, workingSet: false },
          { reps: 2, weight: 175, workingSet: false },
          { reps: 2, weight: 185, workingSet: true },
          { reps: 2, weight: 185, workingSet: true },
          { reps: 2, weight: 185, workingSet: true },
          { reps: 2, weight: 185, workingSet: true },
          { reps: 2, weight: 185, workingSet: true },
          { reps: 2, weight: 185, workingSet: true },
        ],
      },
    ],
  },
  {
    name: "Training #3",
    date: "01-06-2019",
    program: [
      {
        excersise: "Squat",
        sets: [
          { reps: 10, weight: 85, workingSet: false },
          { reps: 8, weight: 125, workingSet: false },
          { reps: 7, weight: 147.5, workingSet: false },
          { reps: 6, weight: 157.5, workingSet: false },
          { reps: 5, weight: 170, workingSet: true },
          { reps: 4, weight: 170, workingSet: true },
          { reps: 3, weight: 170, workingSet: true },
          { reps: 3, weight: 170, workingSet: true },
          { reps: 4, weight: 170, workingSet: true },
        ],
      },
      {
        excersise: "Bench Press",
        sets: [
          { reps: 10, weight: 65, workingSet: false },
          { reps: 8, weight: 87.5, workingSet: false },
          { reps: 7, weight: 100, workingSet: false },
          { reps: 6, weight: 110, workingSet: false },
          { reps: 6, weight: 110, workingSet: false },
          { reps: 6, weight: 110, workingSet: false },
          { reps: 4, weight: 115, workingSet: true },
          { reps: 4, weight: 115, workingSet: true },
          { reps: 4, weight: 115, workingSet: true },
          { reps: 4, weight: 115, workingSet: true },
          { reps: 4, weight: 115, workingSet: true },
          { reps: 4, weight: 115, workingSet: true },
        ],
      },
    ],
  },
];
